EmpCRUD/urls.py
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp_form/',emp_form,name='emp_form'),
    path('emp_display/',emp_display,name='emp_display'),
    path('emp_update/<id>',emp_form,name='emp_update'),
    path('emp_delete/<id>',emp_delete,name='emp_delete'),
    path('filter_data/',filter_data,name='filter_data'),
    path('search/',search,name='search'),
    path('autocomplete/',autocomplete,name='autocomplete'),
]

app/models.py
from django.db import models
from django import forms
import re

# Create your models here.



def name_valid(value):
	if len(value)<=3:
		raise forms.ValidationError('Name length is short')


def age_valid(value):
	if value<=20:
		raise forms.ValidationError('Age must be more then 20')

def mobile_valid(value):
	pattern=re.compile('[6-9][0-9]{9}')
	if not pattern.match(value):
		raise forms.ValidationError('Invalid mobile number')

class Position(models.Model):
	name=models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Employee(models.Model):
	empid=models.IntegerField(primary_key=True)
	name=models.CharField(validators=[name_valid],max_length=100)
	age=models.IntegerField(validators=[age_valid])
	email=models.EmailField()
	mobile=models.CharField(validators=[mobile_valid],max_length=10)
	gender=models.CharField(max_length=6)
	city=models.CharField(max_length=100)
	position=models.ForeignKey(Position,on_delete=models.CASCADE)

	def __str__(self):
		return self.name

app/forms.py
from django import forms
from app.models import *

gender=[
	('Male','Male'),
	('Female','Female')
]

class EmpForm(forms.ModelForm):
	class Meta:
		model=Employee
		fields='__all__'
		widgets={
			'empid':forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Employee Id'}),
			'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Employee Name'}),
			'age':forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Employee Age'}),
			'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter Employee Email'}),
			'mobile':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Employee Mobile'}),
			'gender':forms.RadioSelect(choices=gender),
			'city':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Employee City'}),
			'position':forms.Select(attrs={'class':'form-control'})
		}

	def __init__(self,*args,**kwargs):
		super(EmpForm,self).__init__(*args,**kwargs)
		self.fields['position'].empty_label='---Select Employee Position---'

class FilterForm(forms.ModelForm):
	class Meta:
		model=Employee
		fields=['position']
		widgets={'position':forms.Select(attrs={'class':'form-control'})}

app/views.py
from django.shortcuts import render,redirect
from app.forms import *
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import JsonResponse

# Create your views here.

def emp_form(request,id=0):
	if id==0:
		form=EmpForm()
		if request.method=='POST':
			data=EmpForm(request.POST)
			if data.is_valid():
				name=data.cleaned_data['name']
				data.save()
				messages.success(request,f'{name} Data inserted successfully')
				return redirect('emp_display')
	else:
		ins=Employee.objects.get(empid=id)
		form=EmpForm(instance=ins)
		if request.method=='POST':
			data=EmpForm(request.POST,instance=ins)
			if data.is_valid():
				name=data.cleaned_data['name']
				data.save()
				messages.success(request,f'{name} Data updated successfully')
				return redirect('emp_display')

	return render(request,'employee_form.html',locals())

def emp_display(request):
	data=Employee.objects.all().order_by('empid')
	paginator=Paginator(data,5)
	page=request.GET.get('page')
	pages=paginator.get_page(page)
	form=FilterForm()
	return render(request,'emp_display.html',locals())


def emp_delete(request,id):
	data=Employee.objects.get(empid=id)
	data.delete()
	messages.success(request,f'{data.name} Details deleted successfully')
	return redirect('emp_display')

def filter_data(request):
	if request.method=='GET':
		data=FilterForm(request.GET)
		if data.is_valid():
			id=data.cleaned_data['position']
			fil=Employee.objects.filter(position=id)
	return render(request,'filter_data.html',locals())

def search(request):
	search=request.GET['search']
	if not search=='':
		data=Employee.objects.filter(name__icontains=search)
	return render(request,'search.html',locals())

def autocomplete(request):
	if 'term' in request.GET:
		qs=Employee.objects.filter(name__istartswith=request.GET['term'])
		titles=[]
		for item in qs:
			titles.append(item.name)
		return JsonResponse(titles,safe=False)

templates/dummy.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block title %}
	<title>Dummy</title>
	{% endblock %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
	
  <script
  src="https://code.jquery.com/jquery-3.7.0.min.js"
  integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
  crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
	<style>
		.title{
			height: 60px;
			background-color: deeppink;
			display: flex;
			align-items: center;
			justify-content: center;
		}
	</style>
</head>
<body>
	<div>
		<h2 class="title">Employee Details CRUD operations by using Django</h2>
	</div>
		{% block content %}
		{% endblock %}
	

	
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/emp_display.html
{% extends 'dummy.html' %}

{% block title %}
	<title>Emp Details</title>
	{% endblock %}

{% block content %}
<style>
	label{
		font-weight: bold;
		margin-right: 10px;
		margin-top: 3px;
		font-size: 20px;
	}
	.div{
		display: flex;
		margin-top: 10px;
		align-items: center;
		justify-content: space-between;

	}
	.fo{
		display: inline-flex;
		gap: 10px;
	}
</style>
<div class="col-lg-10 offset-lg-1">
<div class="div">
	<a href="{% url 'emp_form' %}" class="btn btn-primary my-3">Add New Employee</a>
	<form method="GET" action="/search" class="fo">
		<input type="search" name="search" class="form-control" placeholder="Search" id="search">
		<input type="submit" class="btn btn-outline-primary btn-sm">
	</form>
	<form method="GET" action="/filter_data" class="my-3 fo">
	<label>Filter:</label>{{form.position}}
	<input type="submit" class="btn btn-outline-success btn-sm">
	</form>
	
</div>
{% for msg in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>{{msg}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% if pages %}
<table class="table table-bordered">
	<tr class="table-warning">
		<th>Id</th>
		<th>Name</th>
		<th>Age</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Gender</th>
		<th>Position</th>
		<th>Update</th>
		<th>Delete</th>
	</tr>
	{% for i in pages %}
	<tr>
		<td>{{i.empid}}</td>
		<td>{{i.name}}</td>
		<td>{{i.age}}</td>
		<td>{{i.email}}</td>
		<td>{{i.mobile}}</td>
		<td>{{i.gender}}</td>
		<td>{{i.position}}</td>
		<td><a href="{% url 'emp_update' i.empid %}" class="btn btn-warning btn-sm">Update</a></td>
		<td><a href="{% url 'emp_delete' i.empid %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure to delete {{i.name}} details?')">Delete</a></td>
	</tr>
	{% endfor %}
</table>
{% else %}
<h4>Data not available</h4>
{% endif %}
</div>
<!--
{{pages}}<br>
Previous :{{pages.has_previous}}<br>
Next :{{pages.has_next}}<br>
Current :{{pages.number}}<br>
No.of pages :{{pages.paginator.num_pages}}
-->
<div class="text-center">
{% if pages.has_previous %}
<a href="?page=1" class="btn btn-success btn-sm">First</a>
<a href="?page={{pages.previous_page_number}}" class="btn btn-success btn-sm">Previous</a>
{% else %}
<a href="" class="btn btn-success btn-sm disabled">Previous</a>
{% endif %}

Page {{pages.number}} of {{pages.paginator.num_pages}}

{% if pages.has_next %}
<a href="?page={{pages.next_page_number}}" class="btn btn-info btn-sm">Next</a>
<a href="?page={{pages.paginator.num_pages}}" class="btn btn-info btn-sm">Last</a>
{% else %}
<a href="" class="btn btn-info btn-sm disabled">Next</a>
{% endif %}

</div>


<script>
  $( function() {

    $( "#search" ).autocomplete({
      source: "{% url 'autocomplete' %}",
      minLength:2
    });
  } );
  </script>
{% endblock %}

templates/employee_form.html
{% extends 'dummy.html' %}

{% block title %}
	{% if form.instance.empid %}
	<title>Emp Update</title>
	{% else %}
	<title>Emp Create</title>
	{% endif %}
	{% endblock %}

{% block content %}
<style>
	label{
		font-weight: bold;
	}
	#id_gender{
		display: inline-flex;
		gap: 10px;
	}
	span{
		color: red;
	}
</style>
<div class="col-lg-6 offset-lg-3 my-3">
	{% if form.instance.empid %}
	<h3>Employee Updation Form</h3>
	{% else %}
	<h3>Employee Creation Form</h3>
	{% endif %}
	<hr>
	<form method="POST" class="border p-3 rounded-lg border-danger">
		{% csrf_token %}
		<div class="row">
			<div class="col-lg-6">
				<label>Employee Id:</label>{{form.empid}}
				<span>{{data.errors.empid}}</span>
			</div>
			<div class="col-lg-6">
				<label>Employee Name:</label>{{form.name}}
				<span>{{data.errors.name}}</span>
			</div>
		</div>
		<label>Employee Email:</label>{{form.email}}
		<div class="row">
			<div class="col-lg-6">
				<label>Employee Age:</label>{{form.age}}
				<span>{{data.errors.age}}</span>
			</div>
			<div class="col-lg-6">
				<label>Employee Mobile:</label>{{form.mobile}}
				<span>{{data.errors.mobile}}</span>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-6">
				<label class="d-block">Employee Gender:</label>{{form.gender}}
			</div>
			<div class="col-lg-6">
				<label>Employee City:</label>{{form.city}}
			</div>
		</div>
		<label>Employee Position:</label>{{form.position}}
		{% if form.instance.empid %}
		<input type="submit" value="Update" class="my-3 btn btn-success">
		<a href="{% url 'emp_display' %}" class="btn btn-warning ml-5">Go Back</a>
		{% else %}
		<input type="submit" value="Insert" class="my-3 btn btn-primary">
		<a href="{% url 'emp_display' %}" class="btn btn-warning ml-5">View Emp Details</a>
		{% endif %}
	</form>
</div>
{% endblock %}

templates/filter_data.html
{% extends 'dummy.html' %}

{% block title %}
	<title>Emp Details</title>
	{% endblock %}

{% block content %}
<div class="col-lg-10 offset-lg-1 my-4">
<h3>Filter Result = {{id}}</h3>
{% if fil %}
<table class="table table-bordered">
	<tr class="table-warning">
		<th>SNo.</th>
		<th>Id</th>
		<th>Name</th>
		<th>Age</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Gender</th>
		<th>Position</th>
		<th>Update</th>
		<th>Delete</th>
	</tr>
	{% for i in fil %}
	<tr>
		<td>{{forloop.counter}}</td>
		<td>{{i.empid}}</td>
		<td>{{i.name}}</td>
		<td>{{i.age}}</td>
		<td>{{i.email}}</td>
		<td>{{i.mobile}}</td>
		<td>{{i.gender}}</td>
		<td>{{i.position}}</td>
		<td><a href="{% url 'emp_update' i.empid %}" class="btn btn-warning btn-sm">Update</a></td>
		<td><a href="{% url 'emp_delete' i.empid %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure to delete {{i.name}} details?')">Delete</a></td>
	</tr>
	{% endfor %}
</table>
{% else %}
<h4>Data not available</h4>
{% endif %}
</div>
{% endblock %}

templates/search.html
{% extends 'dummy.html' %}

{% block title %}
	<title>Search</title>
	{% endblock %}

{% block content %}
<div class="col-lg-10 offset-lg-1 my-4">
<h3>Search Results</h3>
{% if data %}
<table class="table table-bordered">
	<tr class="table-warning">
		<th>SNo.</th>
		<th>Id</th>
		<th>Name</th>
		<th>Age</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Gender</th>
		<th>Position</th>
		<th>Update</th>
		<th>Delete</th>
	</tr>
	{% for i in data %}
	<tr>
		<td>{{forloop.counter}}</td>
		<td>{{i.empid}}</td>
		<td>{{i.name}}</td>
		<td>{{i.age}}</td>
		<td>{{i.email}}</td>
		<td>{{i.mobile}}</td>
		<td>{{i.gender}}</td>
		<td>{{i.position}}</td>
		<td><a href="{% url 'emp_update' i.empid %}" class="btn btn-warning btn-sm">Update</a></td>
		<td><a href="{% url 'emp_delete' i.empid %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure to delete {{i.name}} details?')">Delete</a></td>
	</tr>
	{% endfor %}
</table>
{% else %}
<h4>Data not available</h4>
{% endif %}
</div>
{% endblock %}